# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  push:
    branches: [dev, master, feat/**, ci/test, test/**]
  pull_request:
    branches: [dev, master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  bootstrap:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, '.md')}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: | 
          pnpm i && pnpm build:only && pnpm build
          node scripts/scripts.js --publishDoc
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bindings-${{matrix.node}}
          path: |
           packages
           !packages/**/node_modules    
  lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: "Lint: node-12, ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: 12
          cache: "pnpm"
      - name: Install dependencies
        run: | 
          pnpm i
      - name: Lint
        run: pnpm lint

  deploy-doc: 
    if: ${{ contains(github.actor, 'zhangyuang') && github.ref_name == 'dev'}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: node scripts/scripts.js --changelog && cd docs && yarn && npm run deploy
        env:
          SERVERLESS_DEPLOY_AK: ${{ secrets.SERVERLESS_DEPLOY_AK }}
          SERVERLESS_DEPLOY_ENDPOINT: ${{ secrets.SERVERLESS_DEPLOY_ENDPOINT }}
          SERVERLESS_DEPLOY_ID: ${{ secrets.SERVERLESS_DEPLOY_ID }}
          SERVERLESS_DEPLOY_SECRET: ${{ secrets.SERVERLESS_DEPLOY_SECRET }}
          SERVERLESS_DEPLOY_TIMEOUT: ${{ secrets.SERVERLESS_DEPLOY_TIMEOUT }}

  e2e-chrome-midway-react:
    needs: bootstrap
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node: ["12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: bindings-${{matrix.node}}
          path: packages
      - uses: cypress-io/github-action@v2
        with:
          install: false
          start: pnpm example:midway:react
          wait-on: 'http://localhost:3000'
          spec: | 
            e2e/integration/examples/common-ssr.spec.js  
            e2e/integration/examples/react-ssr.spec.js
          browser: chrome

  e2e-chrome-nestjs-react-prod:
    needs: bootstrap
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node: ["12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: bindings-${{matrix.node}}
          path: packages
      - uses: cypress-io/github-action@v2
        with:
          install: false
          start: pnpm example:nestjs:react:prod
          wait-on: 'http://localhost:3000'
          spec: | 
            e2e/integration/examples/common-ssr.spec.js  
            e2e/integration/examples/react-ssr.spec.js
          browser: chrome
  e2e-chrome-nestjs-react-prod-vite:
    needs: bootstrap
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node: ["12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: bindings-${{matrix.node}}
          path: packages
      - uses: cypress-io/github-action@v2
        with:
          install: false
          start: pnpm example:nestjs:react:prod:vite
          wait-on: 'http://localhost:3000'
          spec: | 
            e2e/integration/examples/common-ssr.spec.js  
            e2e/integration/examples/react-ssr.spec.js
          browser: chrome
  e2e-chrome-nestjs-vue3-prod-vite:
    needs: bootstrap
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node: ["12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: bindings-${{matrix.node}}
          path: packages
      - uses: cypress-io/github-action@v2
        with:
          install: false
          start: pnpm example:nestjs:vue3:prod:vite
          wait-on: 'http://localhost:3000'
          spec: | 
            e2e/integration/examples/common-ssr.spec.js  
            e2e/integration/examples/vue3-ssr.spec.js
          browser: chrome
  e2e-chrome-nestjs-vue-prod:
    needs: bootstrap
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node: ["12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: bindings-${{matrix.node}}
          path: packages
      - uses: cypress-io/github-action@v2
        with:
          install: false
          start: pnpm example:nestjs:vue:prod
          wait-on: 'http://localhost:3000'
          spec: | 
            e2e/integration/examples/common-ssr.spec.js  
            e2e/integration/examples/vue-ssr.spec.js
          browser: chrome
  e2e-chrome-nestjs-vue3-prod:
    needs: bootstrap
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node: ["12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: bindings-${{matrix.node}}
          path: packages
        
      - uses: cypress-io/github-action@v2
        with:
          install: false
          start: pnpm example:nestjs:vue3:prod
          wait-on: 'http://localhost:3000'
          spec: | 
            e2e/integration/examples/common-ssr.spec.js  
            e2e/integration/examples/vue-ssr.spec.js
          browser: chrome
  e2e-chrome-midway-react-vite:
    needs: bootstrap
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node: ["12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: bindings-${{matrix.node}}
          path: packages
        
      - uses: cypress-io/github-action@v2
        with:
          install: false
          start: pnpm example:midway:react:vite
          wait-on: 'http://localhost:3000'
          spec: | 
            e2e/integration/examples/common-ssr.spec.js  
          browser: chrome
  e2e-chrome-midway-vue3-vite:
    needs: bootstrap
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node: ["12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: bindings-${{matrix.node}}
          path: packages
        
      - uses: cypress-io/github-action@v2
        with:
          install: false
          start: pnpm example:midway:vue3:vite
          wait-on: 'http://localhost:3000'
          spec: | 
            e2e/integration/examples/common-ssr.spec.js  
          browser: chrome
          
  e2e-chrome-midway-react-dynamic-router:
    needs: bootstrap
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node: ["12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i

      - name: Get remote e2e example
        uses: actions/checkout@master
        with:
          repository: zhangyuang/ssr-e2e-example
          path: ssr-e2e-example
          ref: master
          
      - name: Mv e2e example
        run: |
          mv ssr-e2e-example/react-dynamic-router-test example
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: bindings-${{matrix.node}}
          path: packages
        
      - uses: cypress-io/github-action@v2
        with:
          install: false
          start: pnpm example:midway:react:dynamic:router
          wait-on: 'http://localhost:3000'
          spec: | 
            e2e/integration/examples/dynamic-ssr.spec.js  
            e2e/integration/examples/common-ssr.spec.js  
            e2e/integration/examples/react-ssr.spec.js
          browser: chrome
          

  e2e-chrome-midway-vue:
    needs: bootstrap
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node: ["12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: bindings-${{matrix.node}}
          path: packages
        
      - uses: cypress-io/github-action@v2
        with:
          install: false
          start: pnpm example:midway:vue
          wait-on: 'http://localhost:3000'
          spec: |
            e2e/integration/examples/common-ssr.spec.js  
            e2e/integration/examples/vue-ssr.spec.js
          browser: chrome
  e2e-chrome-midway-vue3:
    needs: bootstrap
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node: ["12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: bindings-${{matrix.node}}
          path: packages
        
      - uses: cypress-io/github-action@v2
        with:
          install: false
          start: pnpm example:midway:vue3
          wait-on: 'http://localhost:3000'
          spec: |
            e2e/integration/examples/common-ssr.spec.js  
            e2e/integration/examples/vue-ssr.spec.js
          browser: chrome 
  e2e-chrome-nestjs-vue:
    needs: bootstrap
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node: ["12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: bindings-${{matrix.node}}
          path: packages
        
      - uses: cypress-io/github-action@v2
        with:
          install: false
          start: pnpm example:nestjs:vue
          wait-on: 'http://localhost:3000'
          spec: |
            e2e/integration/examples/common-ssr.spec.js  
            e2e/integration/examples/vue-ssr.spec.js
          browser: chrome
  e2e-chrome-nestjs-vue3:
    needs: bootstrap
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node: ["12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: bindings-${{matrix.node}}
          path: packages
        
      - uses: cypress-io/github-action@v2
        with:
          install: false
          start: pnpm example:nestjs:vue3
          wait-on: 'http://localhost:3000'
          spec: |
            e2e/integration/examples/common-ssr.spec.js  
            e2e/integration/examples/vue-ssr.spec.js
          browser: chrome
  publish:
    name: Publish
    if: "startsWith(github.event.head_commit.message, 'chore(release): publish')"
    runs-on: ubuntu-latest
    needs:  
      - lint
      - e2e-chrome-midway-react
      - e2e-chrome-midway-react-vite
      - e2e-chrome-midway-vue
      - e2e-chrome-midway-vue3
      - e2e-chrome-midway-vue3-vite
      - e2e-chrome-midway-react-dynamic-router
      - e2e-chrome-nestjs-react-prod
      - e2e-chrome-nestjs-react-prod-vite
      - e2e-chrome-nestjs-vue-prod
      - e2e-chrome-nestjs-vue3-prod
      - e2e-chrome-nestjs-vue3-prod-vite
      - e2e-chrome-nestjs-vue
      - e2e-chrome-nestjs-vue3

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: bindings-12
          path: packages
      - name: List packages
        run: ls -R packages
        shell: bash
      - name: Lerna publish
        run: |
          find ./packages/ -type d -maxdepth 1 -exec cp LICENSE {} \;
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          npx lerna publish from-package --no-verify-access --yes
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
